{"name": "test03_mis_audit_article", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable", "trace": "self = <scripts.test02_mis.TestMis object at 0x00000264CCD43D90>\n\n    def test03_mis_audit_article(self):\n>       r = self.mis.url_article_audit()\nE       TypeError: 'str' object is not callable\n\nscripts\\test02_mis.py:32: TypeError"}, "start": 1617424981892, "stop": 1617424981892, "uuid": "7b3257e3-f3c3-4148-892d-4c8681405db2", "historyId": "06c46721f8b4c1013c7f0091b51c4ceb", "testCaseId": "ca7660fd3a8bd8fa63dc8a67ce252269", "fullName": "scripts.test02_mis.TestMis#test03_mis_audit_article", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "fanxx"}, {"name": "thread", "value": "3160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}