{"name": "test03_mis_audit_article", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable", "trace": "self = <scripts.test02_mis.TestMis object at 0x0000029B5F48A6D0>\n\n    def test03_mis_audit_article(self):\n>       r = self.mis.url_article_audit()\nE       TypeError: 'str' object is not callable\n\nscripts\\test02_mis.py:32: TypeError"}, "start": 1617425052616, "stop": 1617425052616, "uuid": "785587e7-a38a-41d3-9f0d-e2460a0d3d66", "historyId": "06c46721f8b4c1013c7f0091b51c4ceb", "testCaseId": "ca7660fd3a8bd8fa63dc8a67ce252269", "fullName": "scripts.test02_mis.TestMis#test03_mis_audit_article", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "fanxx"}, {"name": "thread", "value": "16140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}