[32mINFO    [0m root:api_mis.py:27 正在调用后台管理系统 审核文章接口，请求数据：{'article_ids': ['7'], 'status': 2}，请求信息头：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTc0NjEzNTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.1ViL5TZ0lZ1MDN2hAixcRzHHenzoBDdSFtaKdxm5RT8'}
[32mINFO    [0m root:tool.py:19 正在调用公共断言方法。。。。。。
[31m[1mERROR   [0m root:test02_mis.py:36