[32mINFO    [0m root:api_mis.py:27 正在调用后台管理系统 审核文章接口，请求数据：{'article_ids': ['7'], 'status': 2}，请求信息头：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTc0NjE4MDksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.juFlCpPcYUIJgf9HFHS4Rl4IEymlxb5sFS7rwgBXWuo'}
[32mINFO    [0m root:tool.py:19 正在调用公共断言方法。。。。。。
[1m[31mERROR   [0m root:test02_mis.py:37